### ISSUE TITLE
Import is empty - almost

### ISSUE THREAD

**Issue by jezzdk** [luckymarmot/Paw-OpenAPI3Importer#12]
First off, I dont have a menu item in "File" that says "Import OpenAPI 3", so I've tried the File, Text and URL options instead. The result is the same.

This is my json file: https://gsv-navision-api.herokuapp.com/docs/api.json

This is how it looks after an import:

![Screenshot 2021-06-16 at 15 32 53](https://user-images.githubusercontent.com/139632/122228484-2c737300-ceb8-11eb-9302-e5ad6c0ebf52.png)

All the request groups are empty and the only created request is deficient.

**Comment by imclint21** [comment]
Hi,

The same problem, I get this message:

<img width="1210" alt="Screenshot 2021-06-16 at 17 17 01" src="https://user-images.githubusercontent.com/5221349/122235813-ac083e80-cec6-11eb-8b7b-ffdc3fa096dc.png">

**Comment by mshahat** [comment]
the same 👎 , Paw seems to be useful for some people ... I've paid for it 3 years ago and yet every time I try to make use of it , it disappoints. Response times on issues on twitter and emails are really slow. will be great news if we get inputs on this. 

Thanks in advance

**Comment by pongstr** [comment]
@jezzdk @clintnetwork  I've stub a patch to potentially fix your issues. Please see [0.1.1-beta.2](https://github.com/luckymarmot/Paw-OpenAPI3Importer/releases/tag/0.1.1-beta.2),  [Downloadable Zip
](https://github.com/luckymarmot/Paw-OpenAPI3Importer/releases/download/0.1.1-beta.2/com.luckymarmot.PawExtensions.OpenAPI3Importer.zip)

Let me know if there are any other issues, we'll try our best to get this extension stable. Thanks!

**Comment by imclint21** [comment]
Hi

Still have this message:
```
Import process has successfully completed but no new items have been added to your document.
```

My Open API swagger file is: <https://pastebin.com/raw/uV9TeVz8>

**Comment by pongstr** [comment]
hi @clintnetwork, I tried to validate your schema using these openapi validator tools:

- https://apitools.dev/swagger-parser/online/
- https://validator.swagger.io/

it seems that "paths.events.responses" cannot be an empty object ([see the required field here](https://swagger.io/specification/#response-object)), adding a description field should fix the issue like so: 

```javascript
{
  ...
  "paths": {
      "/events": {
      "summary": "Events",
      "get": {
        "tags": [
          "Events"
        ],
        "summary": " WebSocket Real-Time Notifications (SignalR)",

        // Please see OpenAPI docs in regards to responses: https://swagger.io/specification/#responses-object 
        // - The default MAY be used as a default response object for all HTTP codes that are not covered individually by the specification.
        // - The Responses Object MUST contain at least one response code, and it SHOULD be the response for a successful operation call.
        "responses": {

          // In addition, a response object cannot be an empty object, the "description" 
          // field is required see https://swagger.io/specification/#response-object 
          "default": { 
            "description": ""
          },
 
          // optional responses...

          "200": {
            "description": "..."
          },

          "401": {
            "description": "..."
          }
        }
      }
    }
  }
}
```

after these corrections, the document imports the requests successfully. Please do note though that the plugin right now doesn't have a way to fill-in required fields (and perhaps we should add that feature as well).

thanks

**Comment by jezzdk** [comment]
@pongstr I've been able to import my schema with the version you linked to. However I still don't have the option to explicitly import OpenAPI 3. I get an option to select the format _after_ the import has started, however, because it fails to recognise it as OpenAPI 3.

**Comment by pongstr** [comment]
@jezzdk I understand your issue. I'll ask around with the team on how we can add the option to the File Menu, and will get back with you as I figured something out.

**Comment by imclint21** [comment]
Oh okey, thank you!

In fact I use swashbuckle and I created a custom endpoint so I surely do mistakes.

**Comment by imclint21** [comment]
Finally I removed this `/events` endpoint, the import is done but I only see that:

<img width="245" alt="Screenshot 2021-06-21 at 12 21 21" src="https://user-images.githubusercontent.com/5221349/122739005-32d46700-d28b-11eb-9b3e-26c34f6ad160.png">

**Comment by pongstr** [comment]
@clintnetwork please try to validate your openapi document first (please see the validators tools above), as pointed out earlier, this extension does not support fixing invalid documents/schemas, or filling-in required object fields.

**Comment by philprime** [comment]
Hi, I also get the message `No items imported` when loading the official Apple App Store Connect API documentation.

It can be found here: 

- https://developer.apple.com/documentation/appstoreconnectapi
- https://developer.apple.com/sample-code/app-store-connect/app-store-connect-openapi-specification.zip
